language:
  node_js
node_js:
  - lts/*
install:
  - npm install -g codecov
  - npm install -g tap
  - npm install -g jest
  - npm install --save-dev babel-cli babel-preset-env jest supertest superagent
