language:
  node_js
node_js:
  - lts/*
services:
  - mysql
script:
  - npm start && npm test
install:
  - npm install -g codecov
  - npm install -g tap
  - npm install -g jest
  - npm install -g babel-cli
  - npm install -g babel-preset-env
  - npm install supertest --save-dev
  - npm install -g superagent
  - npm install -g nock
